#include "GPIO_port.h"

MTF_GPIO_PORT GPIO_PA[16];
MTF_GPIO_PORT GPIO_PB[16];
MTF_GPIO_PORT GPIO_PC[16];
MTF_GPIO_PORT GPIO_PD[16];
MTF_GPIO_PORT GPIO_PE[16];
MTF_GPIO_PORT GPIO_PF[16];

void MTF_GPIO_Init(MTF_GPIO_PORT *GPIOx, MTF_GPIO_Type *GPIO_Init)
{
    GPIOx[GPIO_Init->Pin].direction = GPIO_Init->Mode;
}
